# Generated by Django 4.1.5 on 2023-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ship_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('docking_date', models.DateTimeField()),
                ('reference', models.CharField(max_length=250)),
                ('reminder_type', models.CharField(max_length=10)),
                ('reminder_date', models.DateTimeField()),
                ('reminder_days', models.IntegerField()),
            ],
        ),
    ]
