# Generated by Django 4.1.5 on 2023-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_details',
            name='docking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ship_details',
            name='reminder_date',
            field=models.DateField(),
        ),
    ]
