# Generated by Django 4.1.5 on 2023-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertSystem', '0002_alter_ship_details_docking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_details',
            name='reference',
        ),
        migrations.AddField(
            model_name='ship_details',
            name='undocking_date',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
    ]
