# Generated by Django 4.1.5 on 2023-01-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertSystem', '0003_remove_ship_details_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_details',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
